"""
simulated_stealer.py

Educational demo that reads the fake Local State and Login Data
generated by generate_fake_browser_data.py and decrypts the dummy passwords.

This script intentionally works ONLY with the fake profile created by the generator.
Do NOT point it to a real browser profile.
"""

import os
import json
import base64
import sqlite3
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

OUT_DIR = "fake_profile"
LOCAL_STATE = os.path.join(OUT_DIR, "Local State")
LOGIN_DB = os.path.join(OUT_DIR, "Login Data")


def load_local_state():
    if not os.path.exists(LOCAL_STATE):
        raise FileNotFoundError("Local State not found. Run the generator first.")
    with open(LOCAL_STATE, "r", encoding="utf-8") as f:
        data = json.load(f)
    enc_key_b64 = data.get("os_crypt", {}).get("encrypted_key")
    if not enc_key_b64:
        raise ValueError("No encrypted_key found in Local State.")
    key_bytes = base64.b64decode(enc_key_b64)
    return key_bytes


def read_login_db():
    if not os.path.exists(LOGIN_DB):
        raise FileNotFoundError("Login Data not found. Run the generator first.")
    conn = sqlite3.connect(LOGIN_DB)
    c = conn.cursor()
    c.execute("SELECT origin_url, username_value, password_value FROM logins")
    rows = c.fetchall()
    conn.close()
    return rows


def decrypt_password(key_bytes, blob_b64):
    raw = base64.b64decode(blob_b64)
    # stored as nonce(12) + ciphertext+tag
    nonce = raw[:12]
    ct = raw[12:]
    aesgcm = AESGCM(key_bytes)
    try:
        plaintext = aesgcm.decrypt(nonce, ct, None)
        return plaintext.decode("utf-8")
    except Exception as e:
        return f"<decryption failed: {e}>"


def main():
    print("[*] Loading fake Local State key...")
    key = load_local_state()
    print("[*] Reading fake Login Data entries...")
    rows = read_login_db()
    print("\nDecrypted credentials (SIMULATION):\n")
    for origin, user, blob in rows:
        pwd = decrypt_password(key, blob)
        print(f"Origin: {origin}")
        print(f"Username: {user}")
        print(f"Password: {pwd}")
        print("-" * 40)
    print("\n[!] End of simulation. These were dummy entries created locally.")


if __name__ == "__main__":
    main()
